@startuml Class
class User {
    UUID id
    String userName
    String passwordHash
    String bio
    LocalDateTime created
}

class UserInterest {
    UUID userId
    String interestId
}

enum EventType {
    MEETUP
    SERVICE
}

class Event {
    UUID id
    UUID ownerId
    EventType type
    int capacity
    String category
    String title
    String details
    double latitude
    double longitude
    String cityName
    String countryName
    LocalDateTime startDateTime
    LocalDateTime endDateTime
    LocalDateTime created
}

class EventUser {
    UUID eventId
    UUID userId
}

class Follow {
    Long id
    UUID followerId
    UUID followeeId
    LocalDateTime created
}

class Interest {
    String name
}

class Rating {
    UUID id
    UUID raterId
    UUID ratedId
    UUID eventId
    int rating
    LocalDateTime created
}

class Message {
    UUID id
    UUID senderId
    UUID receiverId
    String text
    LocalDateTime created
}

class Notification {
    UUID id
    UUID recipientId
    String htmlText
    String deeplink
    LocalDateTime created
}

class JoinRequest {
    UUID id
    UUID eventId
    UUID userId
    LocalDateTime created
}

@enduml
