@startuml UseCase
left to right direction
skinparam packageStyle rectangle
actor user
actor event_participant
user <|-- event_creator
user <|-- event_participant
rectangle system {
    user --> (sign up)
    user --> (get profile)
    user --> (update profile)
    user --> (delete profile)
    user --> (create event)
    user --> (get single event)
    user --> (get event feed)
    user --> (get events of user)
    user --> (get event feed of followed users)
    user --> (get event participants)
    user --> (create join request)
    user --> (get notifications)
    user --> (get messages)
    user --> (send message)
    user --> (get conversations)
    user --> (add follow)
    user --> (delete follow)
    user --> (authenticate)
    user --> (logout)
    user --> (get followers of a user)
    user --> (get followees of a user)
    user --> (get pending rating requests)
    event_creator --> (approve join request)
    event_creator --> (reject join request)
    event_creator --> (get pending join requests)
    event_participant --> (rate event creator)
    event_creator --> (rate participant)
    event_creator --> (get event participants)
}

@enduml
